name: Build

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: run linters
        run: npm run lint

      - name: run unit tests
        run: npm run test:unit

      - name: build docker image
        run: docker compose build auth-wiedersehen-web
