name: PR Validation

on:
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: run linters
        run: npm run lint

      - name: run unit tests
        run: npm run test:coverage

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/cobertura-coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          output: both
          thresholds: '60 90'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: build docker image
        run: docker compose build auth-wiedersehen-web